COUNTRY_GROUPS = [
    [
        "Cambodia",
        "China",
        "Fiji",
        "Laos",
        "Malaysia",
        "Mongolia",
        "Papua New Guinea",
        "Philippines",
        "Korea, South",
        "Vietnam",
    ],
    ["Australia", "Brunei", "Japan", "New Zealand", "Singapore"],
    ["Bangladesh", "Bhutan", "India", "Maldives", "Nepal", "Timor-Leste",],
    ["Indonesia", "Sri Lanka", "Thailand"],
    [
        "Belarus",
        "Estonia",
        "Hungary",
        "Kazakhstan",
        "Latvia",
        "Lithuania",
        "Moldova",
        "Russia",
        "Ukraine",
    ],
    [
        "Andorra",
        "Austria",
        "Belgium",
        "Croatia",
        "Czechia",
        "Denmark",
        "Finland",
        "France",
        "Germany",
        "Greece",
        "Iceland",
        "Ireland",
    ],
    [
        "Israel",
        "Italy",
        "Luxembourg",
        "Malta",
        "Monaco",
        "Netherlands",
        "Norway",
        "Portugal",
        "San Marino",
        "Slovenia",
        "Spain",
        "Sweden",
        "Switzerland",
        "United Kingdom",
    ],
    [
        "Afghanistan",
        "Djibouti",
        "Egypt",
        "Iraq",
        "Morocco",
        "Pakistan",
        "Somalia",
        "Sudan",
    ],
    [
        "Bahrain",
        "Cyprus",
        "Iran",
        "Jordan",
        "Kuwait",
        "Lebanon",
        "Libya",
        "Oman",
        "Qatar",
        "Saudi Arabia",
        "Syria",
        "Tunisia",
        "United Arab Emirates",
    ],
    ["Bolivia", "Ecuador", "Guatemala", "Haiti", "Nicaragua", "Peru"],
    [
        "Antigua and Barbuda",
        "Argentina",
        "Bahamas",
        "Barbados",
        "Belize",
        "Brazil",
        "Chile",
        "Colombia",
        "Costa Rica",
        "Dominican Republic",
        "El Salvador",
        "Grenada",
        "Guyana",
        "Honduras",
        "Jamaica",
    ],
    [
        "Mexico",
        "Panama",
        "Paraguay",
        "Saint Kitts and Nevis",
        "Saint Lucia",
        "Saint Vincent and the Grenadines",
        "Suriname",
        "Trinidad and Tobago",
        "Uruguay",
        "Venezuela",
    ],
    ["Canada", "Cuba", "US"],
    [
        "Botswana",
        "Burundi",
        "Central African Republic",
        "Cote d'Ivoire",
        "Eritrea",
        "Ethiopia",
        "Kenya",
        "Malawi",
        "Mozambique",
        "Namibia",
        "Rwanda",
        "South Africa",
        "Eswatini",
        "Uganda",
        "Zambia",
        "Zimbabwe",
    ],
    [
        "Algeria",
        "Angola",
        "Benin",
        "Burkina Faso",
        "Cameroon",
        "Cabo Verde",
        "Chad",
        "Equatorial Guinea",
        "Gabon",
        "Gambia",
        "Ghana",
        "Guinea",
        "Guinea-Bissau",
        "Liberia",
        "Madagascar",
        "Mali",
        "Mauritania",
        "Mauritius",
        "Niger",
        "Nigeria",
        "Senegal",
        "Seychelles",
        "Sierra Leone",
        "Togo",
    ],
]
